# Sample information
SAMPLES:
  - "1285_covaris2_DNA_10ng_1_S1_L008"
  - "1285_covaris2_DNA_10ng_2_S2_L008"
  - "1285_covaris2_DNA_50ng_S3_L008"
  - "1285_covaris2_DNA_200ng_S4_L008"
LANE: "L001"
RG_NAME: "tissue"

# Read names
FQ_READ_ONE: "R1"
FQ_READ_TWO: "R2"
FQ_READ_UMI: "R3"

# Adapter sequences
ADAPTER_FWD: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
ADAPTER_REV: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT"

# Reference info
REF_GENOME: "~/XTHS-analysis/data/genome/hg19/hg19.fa"
BED: "~/XTHS-analysis/data/bed/S06588914_Regions.bed"
FGBIO_JAR: "~/XTHS-analysis/code/fgbio/target/scala-2.12/fgbio-0.7.0-9b76546-SNAPSHOT.jar"

# CPU information
RAM: 20 # Gigabyes
THREADS: 2

# Project directory
PROJECT_DIR: "/scratch/dana"
