SAMPLES:
  - "1285_covaris2_DNA_10ng_1_S1_L008"
  - "1285_covaris2_DNA_10ng_2_S2_L008"
  - "1285_covaris2_DNA_50ng_S3_L008"
  - "1285_covaris2_DNA_200ng_S4_L008"
REF_GENOME: "/home/dnachman/XTHS-analysis/data/genome/hg19/hg19.fa"
BED: "/home/dnachman/XTHS-analysis/data/bed/S06588914_Regions.bed"
AGENT_DIR: "/home/dnachman/XTHS-analysis/code/AGeNT"
OUT_DIR: "/scratch/dana"
