# Sample information
SAMPLES:
  - "hybr1_S1"
  - "hybr1_S2"
  - "hybr1_S4"
  - "hybr1_S5"
  - "hybr2_S6"
  - "hybr3_S7"
  - "hybr4_S8"
  - "hybr4_S9"
  - "hybr5_S10"
  - "hybr5_S11"

LANE: "L001"
RG_NAME: "tissue"

# Read names
FQ_READ_ONE: "R1"
FQ_READ_TWO: "R2"
FQ_READ_UMI: "R3"

# Adapter sequences
ADAPTER_FWD: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
ADAPTER_REV: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT"

# Reference info
REF_GENOME: "~/XTHS-analysis/data/genome/hg19/hg19.fa"
BED: ""
INTERVAL_LIST: "~/XTHS-analysis/data/interval_list/hg19_3131601_AIO_SolidTumor_Covered.interval_list"

#SOFTWARE
FGBIO_JAR: "~/XTHS-analysis/code/fgbio/target/scala-2.12/fgbio.jar"
PICARD_JAR: "~/miniconda3/share/picard-2.18.14-0/picard.jar"

# CPU information
RAM: 25 # Gigabyes
THREADS: 2

# Project directory
PROJECT_DIR: "/scratch/dana"
